/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include"led.h"
#include "lis3dsh.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//char str[32];
	int ret;
	LIS_Data val;
	SystemInit();
	LedInit(LED_RED);
	LedInit(LED_ORANGE);
	LedInit(LED_BLUE);
	LedInit(LED_GREEN);
	LIS_Init();
	DelayMs(100);
	while(1) {
		ret = LIS_DRdy();
		if(ret) {
			val = LIS_GetData();
			//sprintf(str, "X=%d, Y=%d", val.x, val.y);
			//LcdPuts(LCD_LINE1, str);
			//sprintf(str,"Z=%d",val.z);
			//LcdPuts(LCD_LINE2, str);
			DelayMs(100);
			if(val.x > 1000){
				LedOn(LED_RED);
			}
			else{
				LedOff(LED_RED);
			}
			if(val.x < -2500){
				LedOn(LED_GREEN);
			}
			else{
				LedOff(LED_GREEN);
			}
			if(val.y > 2500){
				LedOn(LED_ORANGE);
			}
			else{
				LedOff(LED_ORANGE);
			}
			if(val.y < -3000){
				LedOn(LED_BLUE);
			}
			else{
				LedOff(LED_BLUE);
			}
		}
	}
	return 0;
}
