/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "adc.h"
#include "switch.h"
#include "i2c_lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	char str1[32];
	char str2[32];
	uint16_t val;
	SystemInit();
	ADC_Init();
	LcdInit();
	sprintf(str2,"LDR Assignment");
	LcdPuts(LCD_LINE1, str2);
	SwitchInit(SWITCH);
	while(1) {
	                while(exti0_flag == 0)
	                	;
					val = ADC_GetValue();
					//LcdPuts(LCD_CMD,LCD_CLEAR);
					sprintf(str1,"LDR Output= %d", val);
					LcdPuts(LCD_LINE2, str1);
					DelayMs(20);
					exti0_flag = 0;


	}
	return 0;
}
