/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "led.h"
#include "switch.h"
#include "lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	LedInit(LED_ORANGE);
	SwitchInit(SWITCH);

	int counter = 0;
	char str[30];
	while(1) {

		while(exti0_flag == 0)
			;

		LedBlink(LED_ORANGE, 500);
		LcdInit();
		counter++;
			sprintf(str, "CNT=%d", counter);
			LcdPuts(LCD_LINE1,"Assignment04 ");
			LcdPuts(LCD_LINE2, str);

			exti0_flag = 0;
	}
	return 0;
}
